### ISSUE TITLE
Action method paths

### ISSUE THREAD

**Issue by lylax47** [czcorpus/kontext#1114]
#### I was wondering how to change the action method path. I tried editing <action_path_prefix> body to read "/var/www/kontext/cmpltmpl" in config.xml (formerly /apps/kontext), because Kontext was searching for action methods in /var/www/apps, which doesn't exist. First off is the aforementioned path correct, and if so how do I redirect Kontext there? The following is from the apache error logs:

[Wed May 11 17:20:51 2016] [error] [client 127.0.0.1] File does not exist: /var/www/kontext/public/files/themes/autumn_mood, referer: http://localhost/kontext/first_form
[Wed May 11 17:20:51 2016] [error] [client 127.0.0.1] File does not exist: /var/www/kontext/public/files/themes/autumn_mood, referer: http://localhost/kontext/first_form
[Wed May 11 17:20:52 2016] [error] [client 127.0.0.1] File does not exist: /var/www/user, referer: http://localhost/kontext/first_form

**Comment by tomachalek** [comment]
### action_path_prefix

The  *\<action_path_prefix\>* can be used to correct URLs KonText generates for HTML links, loaded scripts/images/etc. A good starting point is to set it to an empty value  (i.e. *\<action_path_prefix /\>*). KonText generates its URLs using HTTP request properties and in many cases it does not need any additional information to produce correct URLs. 

But in some installations (typically if it is behind some proxy server(s) or if it is installed in a non root location (e.g. http://some-domain/some-directory which seems to be your case), KonText may not know about the whole URL path. In such case you can configure the missing part by adding it to *\<action_path_prefix\>* (e.g. *\<action_path_prefix>/kontext\<action_path_prefix\>*). You can always check some links on KonText homepage (e.g. the ones in the main menu) and if they point your browser to *http://localhost* instead of *http://localhost/kontext* then you should set *action_path_prefix* to */kontext*.

### log error

The log you attached here seems to expose other misconfiguration. It can be fixed by setting the *kontext/theme/name* element to *default*.

**Comment by lylax47** [comment]
I should probably explain more what I am trying to do, as this may require additional configuration, which I haven't yet added. I am trying to get the other functions besides basic corpus queries to function, which requires one to create a user id. Currently when I try to do so, it raises a 404 error. I thought that it may have to do with the action path needing to be adjusted, which is why I asked above, but I tried what you suggested, and am getting the same error.

##### Error:
[Fri May 13 13:34:30 2016] [error] [client 127.0.0.1] File does not exist: /var/www/user, referer: http://localhost/kontext/first_form

**Comment by tomachalek** [comment]
If you want to add a new action method (i.e. a method accessible via HTTP requests) you have actually two options.

### 1. modify one of action modules in *lib/actions/** (or add a new one)

This approach is best suited for cases where you want to try something out and do not expect the code to be merged into official KonText repository. Just pick-up an appropriate action module (e.g. *lib/actions/concordance.py* for concordance-related actions, *lib/action/user.py* for user-related ones etc.), then define a method with *@exposed(...)* decorator (see some code in action modules) and you should be able to access the method via HTTP.

You can also add a whole new action module into *lib/actions*. In such case you have to modify *public/app.py* method [load_controller_class](https://github.com/czcorpus/kontext/blob/master/public/app.py#L115) which maps between URL path and action module (in the same way as *users/login* leads to the *login()* method in *actions.user.User* you can define your URL action prefix and a bunch of action methods).


### 2. create a plug-in (or update an existing one) and use its capability to export action methods

This approach is recommended for "official" KonText development as it does not modify core action methods (*lib/actions/**) and can be easily added and removed to/from KonText.

The easiest way is to add an action method to an existing plug-in (e.g. you want to modify the *auth* plug-in by adding some additional functions like "see user's profile"). [Our wiki](https://github.com/czcorpus/kontext/wiki/Plug-ins-introduction#server_side_notes__exporting_custom_actions) contains an information how to do this. Or you can review an existing code examples (e.g. [here](https://github.com/czcorpus/kontext/blob/8b6bf94f18c063bff18534df6d416095b480449e/lib/plugins/default_taghelper.py)).

In case you have an idea for a whole new plug-in type (i.e. not just a custom implementation of an existing type) then you cannot avoid modifying KonText because at least you have to:

* initialize the plug-in (see [initializer.py](https://github.com/czcorpus/kontext/blob/master/lib/initializer.py))
* attach the plug-in somehow to an existing KonText processing worklow (e.g. by modifying an HTML template to contain some widget using your new functionality or by modifying some existing method processing data etc.)
