### ISSUE TITLE
Looking for a sample corplist.xml

### ISSUE THREAD

**Issue by teckart** [czcorpus/kontext#1210]
We are trying to deploy Kontext here in Leipzig but having trouble with the configuration. Could you provide a sample corplist.xml (//corparch/file in config.xml) (for example for the Susanne corpus) or point to an example?

**Comment by tomachalek** [comment]
Hello, 
provided bellow are two examples of *corplist.xml*. The former contains some keywords/tags for easier search, the latter is a minimal configuration with a single corpus.  Few notes first:

* corpus *ident* attribute value is case insensitive (we at the Czech National Corpus use uppercase names there because of legacy reasons)
* corpus *sentence_struct* attribute is used by KonText when using "sentence" view mode (instead of more common "kwic" mode)
* corpus *web* attribute makes KonText generate a link in a respective corpus description box
* *metadata* subtree can be omitted
* keyword *ident* should be without spaces (we are typically even more strict and use just *[a-z_]* chars); it is just an internal identifier - users see labels anyway

### corplist.xml

```xml
<?xml version="1.0" encoding="utf-8" ?>
<kontext>
    <corplist>
        <keywords>
            <keyword ident="synchronic">
                <label lang="cs">synchronní</label>
                <label lang="en">synchronic</label>
            </keyword>
            <keyword ident="diachronic" color="#4333bc">
                <label lang="cs">diachronní</label>
                <label lang="en">diachronic</label>
            </keyword>
            <keyword ident="foreign_lang">
                <label lang="cs">cizojazyčný</label>
                <label lang="en">foreign language</label>
            </keyword>
        </keywords>
        <corpus sentence_struct="p" ident="SUSANNE">
            <metadata>
                <keywords>
                    <item>foreign_lang</item>
                </keywords>
            </metadata>
        </corpus>
        <corpus web="http://www.korpus.cz/syn.php" sentence_struct="s" ident="SYN">
            <metadata>
                <keywords>
                    <item>synchronic</item>
                </keywords>
            </metadata>
        </corpus>
    </corplist>
</kontext>
```

### corplist.xml (minimal)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<kontext>
    <corplist>
        <corpus sentence_struct="p" ident="SUSANNE" />
    </corplist>
</kontext>
```

**Comment by teckart** [comment]
Thank you!
