### ISSUE TITLE
plugins initialised twice if run directly using app.py

### ISSUE THREAD

**Issue by vidiecan** [czcorpus/kontext#1343]
how to test
- set breakpoint to `create_instance` of a used plugin
- run `python app.py`

**Comment by tomachalek** [comment]
This is probably caused by running the app with *use_reloader=True* (see https://github.com/czcorpus/kontext/blob/master/public/app.py#L285). I think the solution would be to make the setting configurable from command line (something like *--use-reloader*). For CI and other automation purposes, this can be set to false.
