### ISSUE TITLE
Need more detailed installation documentation.

### ISSUE THREAD

**Issue by fishfree** [czcorpus/kontext#1858]
I followed the [INSTALL.md ](https://github.com/czcorpus/kontext/blob/master/doc/INSTALL.md)to install Kontext in a Ubuntu 16.04 box. But failed. Could you please give a more detailed documentation, please? It'll be wonderful for a novice to follow a step by step tutorial :-)

**Comment by tomachalek** [comment]
Hello @fishfree, can you please specify where you got stuck? You don't have to provide e detailed description - just to let me know which part of the documentation should I look for. Because at the moment, we have no resources to rewrite the INSTALL.md file as a whole. But we can still make some incremental improvements and help you (and others) to make the installation easier.

**Comment by fishfree** [comment]
@tomachalek Sorry for late reply. Mainly I have 3 questions:

1. In which version of Linux release do you successfully installed Kontext?
2. What's the meaning of every item in the config file? Are there some dependencies to install before installing Kontext？
3. Are there some pitfalls during the installation to avoid?

Thanks!

**Comment by tomachalek** [comment]
Forgotten issue - sorry.

If still relevant, please try install script in `scripts/install/install.sh`.
