### ISSUE TITLE
Cannot share wordlists via link

### ISSUE THREAD

**Issue by msklvsk** [czcorpus/kontext#2151]
Wordlist params are sent as POST and don’t show up in address bar, making wordlist pages unsharable. Extracting params using dev tools and putting them into query string does work.

**Comment by tomachalek** [comment]
We are aware of this issue. The problem is that in general, black/white list can be uploaded along with other args which makes GET request impossible. 

I can see two possible fixes:

1. Use GET in case no black/white list is uploaded
2. Upload black/white list in advance via AJAX, store it for some time on a server, return a reference to the stored file and use it in a GET request

I'll discuss this with my colleague @petrduda and we'll try to come up with something. Or if you have any idea how this should work feel free to share it.

**Comment by msklvsk** [comment]
I would say that the behavior should be at least not worse than bonito, which uses option 1. Ideally, it would always encode everything except lists in a url, plus, if either list is present, a special parameter `hasBlacklist`/`hasWhitelist`. If someone shares such a link Kontext would ask to provide the file. I would avoid option 2 for its implementational and logical complexity. We cannot guarantee we will store user's file forever. But with an “ideal” option, one can always reproduce the results.

**Comment by tomachalek** [comment]
Fixed in the current master branch.
