### ISSUE TITLE
Link with tree query (for parsed corpora)

### ISSUE THREAD

**Issue by stranak** [czcorpus/kontext#405]
Analogous to #404, allow to see the tree of any sentence (with the match on each line) in a tree query system (e.g. http://lindat.mff.cuni.cz/services/pmltq/, configurable).

Possibly visualise the tree there (in the external service) and also show it in the Kontext UI somehow (similarly to the dictionaries)?

**Comment by stranak** [comment]
We want to do this in two separate ways. We will always link to additional view for each line in the concordance:
- [ ] existing treebanks we have in [Tree-Query](http://lindat.mff.cuni.cz/services/pmltq) will link to the sentence in the new "treebank browser" of the Tree-Query service.
- [ ] All corpora with syntactic information will be stored not only in the "vertical" format but we will also store full trees on disk and use a new JS library [JS Treex View](https://github.com/ufal/js-treex-view) that will display a tree view directly in Kontext. 
    - See [Treex::Web](https://lindat.mff.cuni.cz/services/treex-web/). Run a scenarion that produces some trees and view the results. The JS Treex View library will be basically this code.

**Comment by natalink** [comment]
The preliminary implementation of Tree view tool is described here: https://github.com/ufal/lindat-kontext/issues/9 , the respective commits attached. Following are some issues to solve.
1. the trees are displayed in popupbox, and is not draggable (maybe add some function to popupbox.js ?)
2. we could move the symbol of PML-TQ somewhere else - it is displayed at the end of the concordance line now, and on a small screen, you have to scroll to the right in order to see the icon
3. only some of the corpora (at least from Lindat) will have this functionality. So far I just put a condition to view.tmpl ( #if $corpname == 'syntaxtest_cs_a' ), but it should be reimplemented in a more sophisticated way (e.g. like with audio files)  
![tree-view](https://cloud.githubusercontent.com/assets/2538188/13286218/0e91a8b8-db00-11e5-8f91-271e921ef26b.png)

**Comment by tomachalek** [comment]
outdated
