### ISSUE TITLE
view help window - query form (Languages in Migration)

### ISSUE THREAD

**Issue by anetabuckova** [czcorpus/kontext#5145]
If I don't minimize the view of the whole page, the Czech link is outside the table and the German link is not visible (see snip).

<img width="655" alt="Screenshot 2022-06-23 170624" src="https://user-images.githubusercontent.com/108080544/175331772-b52ac6c1-ac13-47e2-8536-cd4bc14cc9e0.png">

**Comment by dlukes** [comment]
Thank you for reporting this issue! I can see this happening irrespective of the corpus selected -- the content overflows the modal window, instead of the modal becoming scrollable. Not sure if this affects other modals as well -- I tried the one that's displayed when editing the query via the breadcrumbs navigation, and that one seems to work fine in this respect.

**Comment by tomachalek** [comment]
Fixed in 7ef0d23134. Now already in production.
